name: workout_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1


#--------------------- PACKAGES ---------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2

  # Product Specific
  flutter_staggered_grid_view: ^0.7.0


#--------------------- ./ PACKAGES END ---------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  #--------------------- LOCAL ASSETS ---------------------#
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  #--------------------- LOCAL FONTS ---------------------#
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/SF-Compact-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Compact-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Compact-Text-RegularItalic.otf
          style: italic
        - asset: assets/fonts/SF-Compact-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Compact-Text-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/SF-Compact-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Compact-Text-Bold.otf
          weight: 800
